DROP DATABASE IF EXISTS MPD;
CREATE DATABASE MPD;
USE MPD;

CREATE TABLE Personne (
per_num SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
per_nom VARCHAR(50) NOT NULL,
per_prenom VARCHAR(50) NOT NULL,
per_adresse VARCHAR(50),
per_ville VARCHAR(50),
CONSTRAINT PK_Personne PRIMARY KEY(per_num)
);

CREATE TABLE Groupe (
gro_num SMALLINT unsigned NOT NULL AUTO_INCREMENT,
gro_libelle VARCHAR(50),
CONSTRAINT PK_Groupe PRIMARY KEY(gro_num)
);

CREATE TABLE Appartient (
PK_Personne SMALLINT UNSIGNED NOT NULL,
PK_Groupe SMALLINT UNSIGNED NOT NULL,
CONSTRAINT FK_P FOREIGN KEY (PK_Personne) REFERENCES Personne(per_num),
CONSTRAINT FK_G FOREIGN KEY (PK_Groupe) REFERENCES Groupe(gro_num)
);