DROP DATABASE if EXISTS papyrus;
CREATE DATABASE papyrus;


CREATE USER 'util1'@'%' IDENTIFIED BY '';
CREATE USER 'util2'@'%' IDENTIFIED BY '';
CREATE USER 'util3'@'%' IDENTIFIED BY '';

GRANT ALL ON papyrus.* TO 'util1'@'%';
GRANT SELECT ON papyrus.* TO 'util2'@'%';
GRANT SHOW ON papyrus.* TO 'utils3'@'%';

USE papyrus;

CREATE TABLE Vente
(
DELLIV SMALLINT NOT NULL,
QT1 INT NOT NULL,
PRIX1 INT NOT NULL,
QT2 INT,
PRIX2 INT,
QT3 INT,
PRIX3 INT,
NUMFOU VARCHAR(25) NOT NULL CHECK,
CODART CHAR(4) NOT NULL CHECK,
CONSTRAINT FK_NUMFOU FOREIGN KEY (NUMFOU) REFERENCES Fournis(NUMFOU),
CONSTRAINT FK_CODART FOREIGN KEY (CODART) REFERENCES Produit(CODART)
);

CREATE TABLE Produit
(
CODART CHAR(4) NOT NULL,
LIBART VARCHAR(30) NOT NULL,
STKALE INT NOT NULL,
STKPHY INT NOT NULL,
QUTEANN INT NOT NULL,
UNIMES CHAR(5) NOT NULL,
CONSTRAINT PK_codart PRIMARY KEY (CODART)
);

CREATE TABLE Fournis
(
NUMFOU VARCHAR(25) NOT NULL,
NOMFOU VARCHAR(25) NOT NULL,
RUEFOU VARCHAR(50) NOT NULL,
POSFOU CHAR(5) NOT NULL,
VILFOU VARCHAR(30) NOT NULL,
CONFOU VARCHAR(15) NOT NULL,
SATISF TINYINT,
CONSTRAINT PK_numfou PRIMARY KEY (NUMFOU)
);

CREATE TABLE Ligcom
(
NUMLIG TINYINT NOT NULL,
QTECDE INT NOT NULL,
PRIUNI VARCHAR(50) NOT NULL,
QTELIV INT,
DERLIV DATETIME(6) NOT NULL,
NUMCOM INT NOT NULL CHECK,
CODART CHAR(4) NOT NULL,
CONSTRAINT PK_numlig PRIMARY KEY (NUMLIG),
CONSTRAINT FK_numcom FOREIGN KEY (NUMCOM) REFERENCES Entcom (NUMCOM),
CONSTRAINT FK_codart FOREIGN KEY (CODART) REFERENCES Produit (CODART)
);

CREATE TABLE Entcom
(
NUMCOM INT NOT NULL AUTO_INCREMENT,
OBSCOM VARCHAR(50),
DATCOM DATE NOT NULL DEFAULT NOW(),
NUMFOU VARCHAR(25) CHECK,
CONSTRAINT PK_numcom PRIMARY KEY (NUMCOM),
CONSTRAINT FK_numfou FOREIGN KEY (NUMFOU) REFERENCES Fournis(NUMFOU)
);

CREATE UNIQUE INDEX index_numfou ON Entcom(NUMFOU);